### ISSUE TITLE
Error on use of Discussions

### ISSUE THREAD

**Issue by barry-bookinglive** [i-lateral/silverstripe-discussions#2]
Hi Mo,

As requested, but with a slight delay, the error... this is after a clean install with latest of eachmoduel and ss v3.1.12

Doing straight to the created discussions page, click start discussion, complete the required fields and submit to produce the error...

[User Deprecated] Commenting::has_commenting is deprecated. Using Commenting::has_commenting is deprecated. Please use the config API instead. Called from Discussion->CommentsForm.
GET /test_discussions/discussions/view/1
Line 172 in C:\xampp\htdocs\test_discussions\framework\dev\Deprecation.php
Source
163             $level = self::$notice_level;
164             if (!$level) $level = E_USER_DEPRECATED;
165 
166             // Then raise the notice
167             if(substr($string,-1) != '.') $string .= ".";
168 
169             $string .= " Called from " . self::get_called_method_from_trace($backtrace, 2) . '.';
170 
171             if($caller) {
172                 user_error($caller.' is deprecated.'.($string ? ' '.$string : ''), $level); 
173             } else {
174                 user_error($string, $level);  
175             }
176  
177         }
178     }
Trace
Commenting::has_commenting is deprecated. Using Commenting::has_commenting is deprecated. Please use the config API instead. Called from Discussion->CommentsForm. 
Deprecation.php:172
Deprecation::notice(2.0,Using Commenting::has_commenting is deprecated. Please use the config API instead) 
Commenting.php:62
Commenting::has_commenting() 
Discussion.php:112
Discussion->CommentsForm() 
ViewableData.php:361
ViewableData->obj(CommentsForm,,,1) 
ViewableData.php:436
ViewableData->XML_val(CommentsForm,,1) 
call_user_func_array(Array,Array) 
SSViewer.php:179
SSViewer_Scope->__call(XML_val,Array) 
SSViewer.php:535
SSViewer_DataPresenter->__call(XML_val,Array) 
.cache.silverstripe-discussions-master.templates.Layout.DiscussionHolder_view.ss:354
SSViewer_DataPresenter->XML_val(CommentsForm,,1) 
.cache.silverstripe-discussions-master.templates.Layout.DiscussionHolder_view.ss:354
include(C:\xampp\htdocs\test_discussions\silverstripe-cache\dev3.cache.silverstripe-discussions-master.templates.Layout.DiscussionHolder_view.ss) 
SSViewer.php:1031
SSViewer->includeGeneratedTemplate(C:\xampp\htdocs\test_discussions\silverstripe-cache\dev3/.cache.silverstripe-discussions-master.templates.Layout.DiscussionHolder_view.ss,ViewableData_Customised,,Array,) 
SSViewer.php:1098
SSViewer->process(ViewableData_Customised,) 
SSViewer.php:1094
SSViewer->process(ViewableData_Customised) 
Controller.php:167
Controller->handleRequest(SS_HTTPRequest,DataModel) 
ContentController.php:198
ContentController->handleRequest(SS_HTTPRequest,DataModel) 
ModelAsController.php:78
ModelAsController->handleRequest(SS_HTTPRequest,DataModel) 
Director.php:370
Director::handleRequest(SS_HTTPRequest,Session,DataModel) 
Director.php:153
Director::direct(/discussions/view/1,DataModel) 
main.php:177

**Comment by mlewis-everley** [comment]
Wow, this is an old issue. I have just been doing quite a major overhall of this module (it far from optimally written originally).

Hopefully this issue should not be happening again, so I am closing this for now. If there are any issues please feel free to re-open.
